export const PANEL_UNIT_CHANGED = 'PANEL_UNIT_CHANGED';
export const FONT_SIZE_CHANGED = 'FONT_SIZE_CHANGED';
export const COLOR_CHANGED = 'COLOR_CHANGED';
export const BACKGROUND_COLOR_CHANGED = 'BACKGROUND_COLOR_CHANGED';
export const FONT_FAMILY_CHANGED = 'FONT_FAMILY_CHANGED';
export const FONT_VARIANT_CHANGED = 'FONT_VARIANT_CHANGED';
export const FONT_CATEGORY_CHANGED = 'FONT_CATEGORY_CHANGED';
export const LOAD_FONT_DATA = 'LOAD_FONT_DATA';